bind_addr = ":8080"
log_level = "debug"
kafka_addr = "localhost:9092"
kafka_topic = "books"
kafka_partition = 0
kafka_timeout = 10
kafka_max_message_size = 1024
kafka_min_batch_size = 0
kafka_max_batch_size = 102400